<!DOCTYPE html>
<html lang="en"><head>
<script src="chapter_forwards_files/libs/clipboard/clipboard.min.js"></script>
<script src="chapter_forwards_files/libs/quarto-html/tabby.min.js"></script>
<script src="chapter_forwards_files/libs/quarto-html/popper.min.js"></script>
<script src="chapter_forwards_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="chapter_forwards_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="chapter_forwards_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="chapter_forwards_files/libs/quarto-html/quarto-syntax-highlighting-48ffa3e5b9d089919c6712c39e5b00f2.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.41">

  <meta name="author" content="Prof.&nbsp;Ji-Woong Chung">
  <title>Forwards and Futures</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="chapter_forwards_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="chapter_forwards_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="chapter_forwards_files/libs/revealjs/dist/theme/quarto-8f3eebe07241f08526c91a7e9cbef8fd.css">
  <link href="chapter_forwards_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="chapter_forwards_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="chapter_forwards_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="chapter_forwards_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="chapter_forwards_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="chapter_forwards_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Forwards and Futures</h1>
  <p class="subtitle">BUSS386 Futures and Options</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Ji-Woong Chung 
</div>
</div>
</div>

</section>
<section id="lecture-outline" class="slide level2">
<h2>Lecture Outline</h2>
<ul>
<li>Definitions of Forwards and Futures</li>
<li>Payoff of Forward vs Futures
<ul>
<li>Daily Settlements &amp; Margin Accounts</li>
</ul></li>
<li>Hedging Using Futures
<ul>
<li>Perfect Hedge</li>
<li>Imperfect Hedge</li>
</ul></li>
<li>Reading: Ch. 1.3–1.4, Ch. 2 and 3</li>
</ul>
</section>
<section id="futures---contract-specifications" class="slide level2">
<h2>Futures - Contract Specifications</h2>
<ul>
<li><strong>Def.</strong> Futures contract is an <strong>agreement</strong> to buy or sell an asset at a certain time in the future for a certain price.</li>
<li>Underlying asset: the asset on which futures contract is based</li>
<li>Futures price: the promised price to trade</li>
<li>Expiration (or delivery) date: the promised date to trade</li>
<li>Contract size: amount of asset that will be delivered under one contract (e.g.&nbsp;One futures contract on corn is to buy/sell 5,000 bushels).</li>
</ul>
</section>
<section id="futures---contract-specifications-1" class="slide level2">
<h2>Futures - Contract Specifications</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Specification</th>
<th style="text-align: left;">Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Contract Name</td>
<td style="text-align: left;">E-mini S&amp;P 500 Futures</td>
</tr>
<tr class="even">
<td style="text-align: left;">Exchange</td>
<td style="text-align: left;">CME Group</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ticker Symbol</td>
<td style="text-align: left;">ES</td>
</tr>
<tr class="even">
<td style="text-align: left;">Contract Size</td>
<td style="text-align: left;">50 times the S&amp;P 500 Index</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tick Size</td>
<td style="text-align: left;">0.25 index points</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tick Value</td>
<td style="text-align: left;">$12.50 per tick</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Settlement Method</td>
<td style="text-align: left;">Cash settlement</td>
</tr>
<tr class="even">
<td style="text-align: left;">Expiration Months</td>
<td style="text-align: left;">March, June, September, December</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Trading Hours</td>
<td style="text-align: left;">Sunday-Friday 5:00 PM - 4:00 PM (CT) with a 1-hour break</td>
</tr>
<tr class="even">
<td style="text-align: left;">Initial Margin</td>
<td style="text-align: left;">$12,000 (varies by broker)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maintenance Margin</td>
<td style="text-align: left;">$10,800 (varies by broker)</td>
</tr>
</tbody>
</table>
<div class="small">
<p>Source: CME Group</p>
</div>
</section>
<section id="futures---terminology" class="slide level2 scrollable">
<h2>Futures - Terminology</h2>
<ul>
<li><p>Long vs.&nbsp;short position</p>
<ol type="1">
<li>Long position: a trader who agrees to <strong>buy</strong> the underlying asset on futures</li>
<li>Short position: a trader who agrees to <strong>sell</strong> the underlying asset on futures</li>
</ol></li>
<li><p><em>e.g.</em> Long position of Futures on 100,000 bushels of corn for December delivery</p></li>
</ul>
</section>
<section id="futures---terminology-1" class="slide level2">
<h2>Futures - Terminology</h2>
<ul>
<li><p>Entering long/short position of futures contract <strong>costs nothing</strong> (cf.&nbsp;buying stock or bond).</p>
<ul>
<li>Except some collateral to be put up.</li>
<li>This is contrasted with buying/selling in option contracts.</li>
</ul></li>
<li><p>Futures price changes as a result of supply and demand.</p>
<ul>
<li><em>e.g.</em> If there are more investors who want to buy corn for December delivery, then the futures price increases.</li>
</ul></li>
<li><p>Futures vs.&nbsp;Spot price</p>
<ul>
<li>Futures price is for <strong>future</strong> delivery.</li>
<li>Spot price is for <strong>immediate</strong> delivery.</li>
</ul></li>
</ul>
</section>
<section id="forward" class="slide level2 scrollable">
<h2>Forward</h2>
<ul>
<li><p><strong>Def.</strong> Forward contract is an <strong>agreement</strong> to buy or sell an asset at a certain time in the future for a certain price.</p></li>
<li><p>Forward price: the promised price to trade</p></li>
<li><p>How is forward different from futures?</p>
<ol type="1">
<li><p>Forward is traded in the OTC market, while futures is traded in the exchange.</p></li>
<li><p>Forward is settled once on the delivery date, while futures is settled every day.</p></li>
<li><p>Futures have greater liquidity but less flexibility than forwards</p></li>
<li><p>In futures, counterparty credit risk is eliminated</p>
<ul>
<li>Clearing House becomes the counterparty to every contract (“novation”)</li>
<li>To enter futures, collateral (margin) must be posted.</li>
</ul></li>
</ol></li>
</ul>
</section>
<section id="hedging-using-forward" class="slide level2 scrollable">
<h2>Hedging Using Forward</h2>
<ul>
<li><p>Suppose that a food company takes a long position of forward contract on corns for delivery in three months. The forward price is $3.70 per bushel.</p></li>
<li><p>Three month later, the spot price turns out to be …</p>
<ol type="1">
<li><p>$3.75 per bushel:</p>
<p>Payoff on the forward is $(3.75 - 3.70) = 0.05</p></li>
<li><p>$3.67 per bushel:</p>
<p>Payoff on the forward is $(3.67 - 3.70) = -0.03</p></li>
</ol></li>
<li><p>Forward/Futures enables an investor to lock in the price for future transaction, thus reducing uncertainty or risk.</p></li>
</ul>
</section>
<section id="hedging-using-forward-1" class="slide level2">
<h2>Hedging Using Forward</h2>
<ul>
<li><strong>Ex.</strong> Consider a farmer who expects to sell 1,000 bushels of corn in three months. The forward price of corn for delivery in three month $3.70 per bushel.</li>
<li><strong>Q1.</strong> To lock in the profit, which position should the farmer take?</li>
<li><strong>Q2.</strong> Three month later, the spot corn price becomes $3.62 per bushel. What is the payoff on the forward to the farmer?</li>
</ul>
</section>
<section id="payoff-of-forward" class="slide level2">
<h2>Payoff of Forward</h2>
<ul>
<li>Forward and futures are very similar to each other, but a <strong>forward</strong> contract is simpler to analyze.</li>
<li>Let <span class="math inline">\(F\)</span> denote the forward price (the promised price to buy/sell at the contract expiration date <span class="math inline">\(T\)</span>).</li>
<li>Payoff of forward contract:</li>
</ul>
<p><span class="math display">\[
\left\{ {\begin{array}{lc}
\text{long position: } ~ &amp; S_T - F \\
\text{short position: } ~ &amp; F - S_T
\end{array}
}
\right.
\]</span></p>
<p>where <span class="math inline">\(S_T\)</span> is the spot price of the underlying asset at the expiration.</p>
<ul>
<li>A forward contract is settled only once on the expiration date, so cash flow occurs only at the expiration.</li>
</ul>
</section>
<section id="payoff-of-forward-example" class="slide level2">
<h2>Payoff of Forward: Example</h2>
<ul>
<li>An agricultural supplier is looking to sell 1,000 barrels of white sugar in six months’ time that are valued at a total price of £10,000.</li>
<li>The supplier is concerned for declining weather conditions in the country of produce that may have an effect on supply and demand, and therefore the price of the sugar.</li>
<li>It agrees to a cash settled forward contract to sell the 1,000 barrels to an international buyer for the spot market price of £10,000.</li>
</ul>
</section>
<section id="payoff-of-futures" class="slide level2">
<h2>Payoff of Futures</h2>
<ul>
<li><p>Suppose we enter a <strong>futures</strong> contract that will expire on date <span class="math inline">\(T\)</span>.</p></li>
<li><p>Unlike forward, the futures will be settled every day.</p></li>
<li><p><em>e.g.</em> Suppose we long futures on gold on day 0 when the futures price is $1,250 per ounce.</p>
<ul>
<li>If later futures prices are as follows, what will be cash flows each day?</li>
</ul></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Day</th>
<th>Futures price</th>
<th>Daily gain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>1,250</td>
<td></td>
</tr>
<tr class="even">
<td>1</td>
<td>1,255</td>
<td>?</td>
</tr>
<tr class="odd">
<td>2</td>
<td>1,248</td>
<td>?</td>
</tr>
<tr class="even">
<td>3</td>
<td>1,242</td>
<td>?</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td>T</td>
<td><span class="math inline">\(F_T\)</span></td>
<td>?</td>
</tr>
</tbody>
</table>
</section>
<section id="payoff-of-futures---closer-look-at-day-1" class="slide level2">
<h2>Payoff of Futures - Closer Look at Day 1</h2>
<div class="columns">
<div class="column" style="width:50;">
<div style="text-align: center;">
<p><img data-src="img/forwards_futures.png"></p>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li><p>On day 1, new futures price turns out to be $1,255.</p></li>
<li><p>The exchange requires the investors from day 0 to abandon the old contract and move to the new one.</p></li>
<li><p>In this settlement, the exchange pays or receives cash to compensate for the price difference.</p>
<ul>
<li>When moving from the old <span class="math inline">\((F_0=1250)\)</span> to the new <span class="math inline">\((F_1=1255)\)</span>, the long-position investor receives $5.</li>
</ul></li>
</ul>
</div></div>
</section>
<section id="payoff-of-futures-1" class="slide level2">
<h2>Payoff of Futures</h2>
<ul>
<li>On day <span class="math inline">\(t\)</span>, the daily settlement for the long position is as follows.</li>
</ul>
<p><span class="math display">\[
\left\{ {\begin{array}{ll}
\text{If } F_t \geq F_{t-1}, ~ &amp; \text{the investor receives }(F_t-F_{t-1}). \\
\text{If } F_t &lt; F_{t-1}, ~ &amp; \text{the investor pays }(F_{t-1}-F_{t}).
\end{array}
}
\right.
\]</span></p>
<ul>
<li><p>In sum, the daily gain for long position is <span class="math inline">\(F_t - F_{t-1}\)</span>.</p></li>
<li><p>The investor starts long position in a new contract with <span class="math inline">\(F_t\)</span>.</p></li>
<li><p><em>e.g.</em> Go back to the previous example. Daily gain/loss from the settlement is as follows.</p></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Day</th>
<th>Futures price</th>
<th>Daily gain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>1,250</td>
<td></td>
</tr>
<tr class="even">
<td>1</td>
<td>1,255</td>
<td><span class="math inline">\((1,255-1,250) = 5\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td>1,248</td>
<td><span class="math inline">\((1,248-1,255) = -7\)</span></td>
</tr>
<tr class="even">
<td>3</td>
<td>1,242</td>
<td><span class="math inline">\((1,242-1,248) = -6\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td>T</td>
<td><span class="math inline">\(F_T\)</span></td>
<td>$(F_{T} - F_{T-1})$</td>
</tr>
</tbody>
</table>
</section>
<section id="payoff-of-futures---cumulative-gain" class="slide level2">
<h2>Payoff of Futures - Cumulative Gain</h2>
<ul>
<li>Suppose we long futures with futures price <span class="math inline">\(F_0\)</span>.</li>
<li>The futures price on following days turns out to be <span class="math inline">\(F_1\)</span>, <span class="math inline">\(F_2\)</span>, <span class="math inline">\(F_3\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(F_T\)</span>.</li>
<li>Assume that the risk-free rate is 0. Then, the cumulative gain from day 1 to day <span class="math inline">\(T\)</span> is</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
&amp; (F_1 - F_0) + (F_2 - F_1) +(F_3 - F_2) + \ldots + (F_T - F_{T-1}) \\
= &amp;  F_T - F_0\\
= &amp; S_T - F_0
\end{aligned}
\]</span></p>
<ul>
<li>This is the same as payoff for long position in forward contract.</li>
</ul>
</section>
<section id="operation-of-margin-accounts" class="slide level2">
<h2>Operation of Margin Accounts</h2>
<ul>
<li>Recall that futures contracts are traded on the exchange.</li>
<li>To prevent investors from defaulting on the contracts, the exchange requires investors to set up a margin account.</li>
<li>When investors enter a position in futures, they are required to deposit <strong>initial margin</strong> (e.g.&nbsp;$3,000 per contract).</li>
<li>Once the margin account is set up, the gain/loss from daily settlement of futures will be added to/subtracted from the account balance.</li>
</ul>
</section>
<section id="operation-of-margin-accounts-1" class="slide level2">
<h2>Operation of Margin Accounts</h2>
<ul>
<li><p>As a result of daily settlements, the balance in the margin account changes time to time.</p></li>
<li><p>During the contract period, investors are also required to maintain the balance at a certain level.</p>
<ul>
<li><strong>Maintenance margin</strong>: the <strong>minimum</strong> amount that must be maintained during the contract.</li>
<li>If the balance in the account falls below the maintenance margin, investors receive a <strong>margin call</strong> from exchange. Then, they need to top up the margin account up to the initial margin.</li>
</ul></li>
</ul>
</section>
<section id="operation-of-margin-accounts---example" class="slide level2">
<h2>Operation of Margin Accounts - Example</h2>
<ul>
<li>On day 0, we long a futures contract on gold at the futures price of $1,250 per ounce. The contract size is 100 ounce per contract.</li>
<li>Initial margin is $3,000 and maintenance margin is $2,000 per contract.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Day</th>
<th>Futures price</th>
<th>Daily gain</th>
<th>Balance</th>
<th>Margin calls</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>1,250</td>
<td></td>
<td>3,000</td>
<td></td>
</tr>
<tr class="even">
<td>1</td>
<td>1,241</td>
<td>$-$900</td>
<td>2,100</td>
<td></td>
</tr>
<tr class="odd">
<td>2</td>
<td>1,238</td>
<td>$-$300</td>
<td>1,800</td>
<td>1,200</td>
</tr>
<tr class="even">
<td>3</td>
<td>1,244</td>
<td>600</td>
<td>3,600</td>
<td></td>
</tr>
<tr class="odd">
<td>4</td>
<td>1,242</td>
<td>$-$200</td>
<td>3,400</td>
<td></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="clearing-house" class="slide level2">
<h2>Clearing House</h2>
<ul>
<li><p>A clearing house keeps track of all the transactions that take place during a day and ``clear’’ the transaction and calculates the net position of each of its members.</p>
<ul>
<li>The clearing house has a number of members. Brokers who are not members themselves must channel their business through a member and post margin with the member.</li>
</ul></li>
<li><p>The clearing house member is required to provide to the clearing house initial margin (clearing margin) reflecting the total number of contracts that are being cleared.</p>
<ul>
<li>Also, the members are required to contribute to a guaranty fund. This may be used by the clearing house in the event that a member defaults and the member’s margin proves insufficient to cover losses.</li>
</ul></li>
<li><p>The whole purpose of the margining system is to ensure that funds are available to pay traders when they make a profit.</p></li>
</ul>
</section>
<section id="delivery-of-futures" class="slide level2 scrollable">
<h2>Delivery of Futures</h2>
<ul>
<li><p>There are two types of delivery of futures:</p>
<ol type="1">
<li>Physical delivery: underlying assets are delivered physically (e.g.&nbsp;commodity)</li>
<li>Cash settlements: final daily gain in futures is paid in cash (e.g.&nbsp;stock index)</li>
</ol></li>
<li><p>Physical delivery may incur additional costs.</p>
<ul>
<li>storage costs</li>
<li>transportation costs</li>
<li>to feed and look after livestock</li>
</ul></li>
</ul>
</section>
<section id="delivery-of-futures-1" class="slide level2">
<h2>Delivery of Futures</h2>
<ul>
<li>It is possible that the physical delivery costs even outweigh the value of underlying assets.</li>
<li><em>e.g.</em> On 20 April 2020, the futures price of WTI crude oil becomes <strong>negative</strong>.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CL=F"</code></pre>
</div>

</div>
<!--       - Global oil demand collapsed due to COVID-19 lockdowns.
      - Oil production remained high as producers couldn't shut down immediately.
      - WTI crude oil futures require physical delivery at Cushing, Oklahoma.
      - By April 2020, Cushing's storage was nearly full.
      - Traders had to sell at any price to avoid taking delivery. -->
<img data-src="chapter_forwards_files/figure-revealjs/unnamed-chunk-1-1.png" class="quarto-figure quarto-figure-center r-stretch" width="1920"></section>
<section id="market-quotes" class="slide level2">
<h2>Market Quotes</h2>
<div style="text-align: center;">
<p><img data-src="img/forwards_gold.png" style="width:110.0%"></p>
</div>
<ul>
<li>Open: the price at which contracts were trading at the beginning of the trading day</li>
<li>High: the highest price during the day</li>
<li>Low: the lowest price during the day</li>
<li>Settlement: the price used for calculating daily gain/loss (usually closing price of the day)</li>
<li>(Trading) Volume: the number of contracts traded in a day</li>
<li>Open interest: the number of contracts outstanding
<ul>
<li>We count the total number of (net) long positions or (net) short positions for a certain contract.</li>
</ul></li>
</ul>
</section>
<section id="hedging-using-futures" class="slide level2 scrollable">
<h2>Hedging Using Futures</h2>
<ul>
<li><p>Hedgers participate in futures market to reduce a particular risk facing them (e.g, fluctuations in oil price, foreign exchange rate).</p></li>
<li><p>To hedge a risk, hedgers take a futures position that neutralizes the risk as much as possible.</p>
<ol type="1">
<li><p>Short hedge: a hedge that involves a short position in futures</p>
<ul>
<li>when a hedger expects to <strong>sell</strong> an asset in the future</li>
</ul></li>
<li><p>Long hedge: a hedge that involves a long position in futures</p>
<ul>
<li>when a hedger expects to <strong>buy</strong> an asset in the future</li>
</ul></li>
</ol></li>
</ul>
</section>
<section id="short-hedge---example" class="slide level2">
<h2>Short Hedge - Example</h2>
<ul>
<li><p>In May, an oil producer enters a sales contract to sell 1 million barrels of crude oil. The price in the sales contract is the spot price on 15 August.</p></li>
<li><p>Oil futures price for August delivery is $79 per barrel, and each contract is for delivery of 1,000 barrels.</p></li>
<li><p>Q. To hedge the risk, what position on futures should the producer take?</p>
<p><span class="math inline">\(\Rightarrow\)</span> short 1,000 futures contract.</p></li>
</ul>
</section>
<section id="short-hedge---example-1" class="slide level2 scrollable">
<h2>Short Hedge - Example</h2>
<p>What if the spot price of oil on 15 August turns out to be …</p>
<ol type="1">
<li>$75 per barrel</li>
</ol>
<p><span class="math display">\[
\text{Total revenue} = \underbrace{75\times 1M}_{\text{sales contract}} + \underbrace{(79-75)\times 1M}_{\text{futures contract}} = 79M
\]</span></p>
<ol start="2" type="1">
<li>$85 per barrel</li>
</ol>
<p><span class="math display">\[
\text{Total revenue} = \underbrace{85\times 1M}_{\text{sales contract}} + \underbrace{(79-85)\times 1M}_{\text{futures contract}} = 79M
\]</span></p>
</section>
<section id="short-hedge---example-2" class="slide level2 scrollable">
<h2>Short Hedge - Example</h2>
<p>What if the spot price of oil on 15 August turns out to be …</p>
<ol type="1">
<li>$75 per barrel</li>
</ol>
<p><span class="math display">\[
\text{Total revenue} = \underbrace{75\times 1M}_{\text{sales contract}} + \underbrace{(79-75)\times 1M}_{\text{futures contract}} = 79M
\]</span></p>
<ol start="2" type="1">
<li>$85 per barrel</li>
</ol>
<p><span class="math display">\[
\text{Total revenue} = \underbrace{85\times 1M}_{\text{sales contract}} + \underbrace{(79-85)\times 1M}_{\text{futures contract}} = 79M
\]</span></p>
</section>
<section id="long-hedge---example" class="slide level2">
<h2>Long Hedge - Example</h2>
<ul>
<li><p>In January, an airline expects to buy 100,000 barrels of jet fuels on 15 May for operation.</p></li>
<li><p>Jet fuel futures price for May delivery is $38.9 per barrel, and each contract is for delivery of 25,000 barrels.</p></li>
<li><p>Q. To hedge the risk, what position on futures should the airline take?</p>
<p><span class="math inline">\(\Rightarrow\)</span> long 4 futures contract.</p></li>
</ul>
</section>
<section id="long-hedge---example-1" class="slide level2 scrollable">
<h2>Long Hedge - Example</h2>
<p>What if the spot price of jet fuel on 15 May turns out to be …</p>
<ol type="1">
<li>$40.0 per barrel</li>
</ol>
<p><span class="math display">\[
\text{Total payment} = \underbrace{40.0\times 100,000}_{\text{sales contract}} - \underbrace{(40.0-38.9)\times 100,000}_{\text{futures contract}} = 3,890,000
\]</span></p>
<ol start="2" type="1">
<li>$37.0 per pound</li>
</ol>
<p><span class="math display">\[
\text{Total payment} = \underbrace{37.0\times 100,000}_{\text{sales contract}} - \underbrace{(37.0-38.9)\times 100,000}_{\text{futures contract}} = 3,890,000
\]</span></p>
</section>
<section id="hedge---general-case" class="slide level2">
<h2>Hedge - General Case</h2>
<ul>
<li>Suppose that on date 0, we expect to sell asset <span class="math inline">\(A\)</span> on date <span class="math inline">\(T\)</span>.</li>
<li>To hedge the risk, we short a certain futures contract.</li>
<li>Total revenue on date <span class="math inline">\(T\)</span> is</li>
</ul>
<p><span class="math display">\[
S_T + (F_0 - F_T)
\]</span></p>
<ul>
<li>Depending on how well the futures contract fits the sales plan, the hedge becomes <strong>perfect</strong> or <strong>imperfect</strong>.</li>
</ul>
</section>
<section id="perfect-hedge" class="slide level2 scrollable">
<h2>Perfect Hedge</h2>
<ul>
<li><p>Perfect hedge means eliminating the risk <strong>completely</strong>, thus leaving no risk.</p></li>
<li><p>The hedge using futures becomes perfect when all of the following conditions are satisfied.</p>
<ol type="1">
<li>The asset whose price is to be hedged is the same as the asset underlying futures contract.</li>
<li>The delivery date of futures contract is the same as the date to buy/sell the underlying asset.</li>
</ol></li>
<li><p>In this case, the total revenue is</p></li>
</ul>
<p><span class="math display">\[
S_T + (F_0 - F_T) = \underbrace{(S_T - F_T)}_{=0} + F_0
\]</span></p>
</section>
<section id="imperfect-hedge" class="slide level2">
<h2>Imperfect Hedge</h2>
<ul>
<li>Sometimes, we <strong>cannot</strong> find a futures with the perfect match.</li>
<li>As a second-best way, we try using an alternative contract with the closest delivery month and on the most similar underlying asset.</li>
<li>The total revenue is</li>
</ul>
<p><span class="math display">\[
S_T + (F_0 - F_T) = \underbrace{(S_T - F_T)}_{\neq 0} + F_0
\]</span></p>
<ul>
<li>This does not eliminate the risk completely.</li>
</ul>
</section>
<section id="basis-risk-and-hedging" class="slide level2">
<h2>Basis Risk and Hedging</h2>
<ul>
<li><p>The basis is the difference between the spot price and the futures price, i.e., <span class="math inline">\(S_t - F_t\)</span>.</p>
<ul>
<li>The futures price and spot price may not move in perfect lockstep. The lack of exact match leads to hedging inaccuracy, known as “basis risk.”</li>
</ul></li>
<li><p>Example</p>
<ul>
<li>On March 1, a U.S. company expects to receive 50 million yen in July.</li>
<li>Yen futures contracts are available for March, June, September, and December, with each contract covering 12.5 million yen.</li>
<li>The company shorts 4 September yen futures contracts on March 1.</li>
<li>When the yen are received in July, the company closes its position.</li>
<li>The futures price on March 1 is <span class="math inline">\(1.0800\)</span> cents per yen, and the spot and futures prices at the end of July are <span class="math inline">\(1.0200\)</span> and <span class="math inline">\(1.0250\)</span> cents per yen, respectively.</li>
<li>The gain on the futures contract is <span class="math inline">\(0.0550\)</span> cents per yen.</li>
<li>The effective price obtained is <span class="math inline">\(1.0200+0.05500=1.0750\)</span> cents per yen.</li>
<li>If a July contract were available with <span class="math inline">\(F_0=1.0800\)</span>, the company could have gotton <span class="math inline">\(1.0200+(1.0800-1.0200)=1.0800\)</span>. The difference <span class="math inline">\(1.0800-1.0750=0.005\)</span> is the basis. Due to undertain about the magnitude of the basis, the company faces risk.</li>
</ul></li>
</ul>
</section>
<section id="perfect-hedge-and-risk-measures" class="slide level2">
<h2>Perfect Hedge and Risk Measures</h2>
<ul>
<li>Suppose that on date 0, an oil company expects to sell gasoline on date <span class="math inline">\(T\)</span>. The gasoline price is normally distributed with the mean of $50 per barrel and the standard deviation of $3 per barrel.</li>
<li>Q. Without hedging, what is the bad outcome of the revenue (per barrel) that will happen 5% probability?</li>
</ul>
</section>
<section id="perfect-hedge-and-risk-measures-1" class="slide level2">
<h2>Perfect Hedge and Risk Measures</h2>
<ul>
<li>Go back to the previous question. This time, the company tries to hedge by shorting a gasoline futures with delivery on <span class="math inline">\(T\)</span>. The futures price is $48 per barrel.</li>
<li>Q1. With the hedging, what is the standard deviation of the revenue?</li>
<li>Q2. With the hedging, what is the bad outcome of the revenue that will happen 5% probability?</li>
</ul>
</section>
<section id="cross-hedge" class="slide level2 scrollable">
<h2>Cross Hedge</h2>
<ul>
<li><p><strong>Cross hedge</strong> is a case of imperfect hedge where we hedge the price risk of an asset using futures on a different underlying asset.</p></li>
<li><p><em>e.g.</em> An airline that is concerned about the future price of jet fuel uses futures contract on heating oil.</p></li>
<li><p>Hedge ratio = size of underlying assets in futures contract/size of exposure</p>
<ol type="1">
<li>In perfect hedge, hedge ratio = 1</li>
<li>In cross hedge, hedge ratio is usually not equal to one. Instead, we choose a particular ratio that will result in the best hedge.</li>
</ol></li>
</ul>
</section>
<section id="cross-hedge---minimum-variance-hedge-ratio" class="slide level2">
<h2>Cross Hedge - Minimum Variance Hedge Ratio</h2>
<ul>
<li><p>In cross hedge, the hedge ratio is chosen to <strong>minimize the variance</strong> of the value of the hedged position.</p></li>
<li><p>Assume that we have one unit of asset <span class="math inline">\(A\)</span> and shorts futures on <span class="math inline">\(h\)</span> units of underlying asset <span class="math inline">\(B\)</span>.</p></li>
<li><p>The value of the hedging portfolio is ..</p>
<ul>
<li><span class="math inline">\(S_0\)</span> at time 0</li>
<li><span class="math inline">\(S_T + h(F_0-F_T)\)</span> at time <span class="math inline">\(T\)</span></li>
</ul></li>
<li><p>The change in the portfolio value is</p></li>
</ul>
<p><span class="math display">\[
\underbrace{S_T -S_0}_{\Delta S} - h\underbrace{(F_T - F_0)}_{\Delta F}
\]</span></p>
</section>
<section id="cross-hedge---minimum-variance-hedge-ratio-1" class="slide level2">
<h2>Cross Hedge - Minimum Variance Hedge Ratio</h2>
<ul>
<li>The variance of the value change is</li>
</ul>
<p><span class="math display">\[
Var(\Delta S) - 2h\times Cov(\Delta S,\Delta F) + h^2 \times Var(\Delta F)
\]</span></p>
<ul>
<li>We want to find <span class="math inline">\(h\)</span> such that minimizes the variance.</li>
<li>To do so, we calculate the derivative of the variance with respect to <span class="math inline">\(h\)</span> and set it equal to 0:</li>
</ul>
<p><span class="math display">\[
h^* = \frac{Cov(\Delta S, \Delta F)}{Var(\Delta F)}
\]</span></p>
<ul>
<li><span class="math inline">\(h^*\)</span> is the minimum variance hedge ratio.</li>
</ul>
</section>
<section id="cross-hedge---minimum-variance-hedge-ratio-2" class="slide level2">
<h2>Cross Hedge - Minimum Variance Hedge Ratio</h2>
<ul>
<li>The hedge ratio can be rewritten as</li>
</ul>
<p><span class="math display">\[
h^* = \rho\frac{\sigma_S}{\sigma_F}
\]</span></p>
<p>where</p>
<ul>
<li><p><span class="math inline">\(\rho\)</span>: the correlation coefficient between <span class="math inline">\(\Delta S\)</span> and <span class="math inline">\(\Delta F\)</span></p></li>
<li><p><span class="math inline">\(\sigma_F\)</span>: the standard deviation of <span class="math inline">\(\Delta F\)</span></p></li>
<li><p><span class="math inline">\(\sigma_S\)</span>: the standard deviation of <span class="math inline">\(\Delta S\)</span></p></li>
<li><p>Alternative interpretation: <span class="math inline">\(h^*\)</span> is the best estimate representing the linear relationship between <span class="math inline">\(\Delta S\)</span> and <span class="math inline">\(\Delta F\)</span>.</p></li>
</ul>
</section>
<section id="cross-hedge---example" class="slide level2">
<h2>Cross Hedge - Example</h2>
<ul>
<li>An airline expects to purchase two million gallons of jet fuel in one month and decides to use heating oil futures for hedging. The standard deviation of futures price is <span class="math inline">\(\sigma_F=0.0313\)</span>, the standard deviation of jut fuel price is <span class="math inline">\(\sigma_S=0.0263\)</span>, and the correlation coefficient is <span class="math inline">\(\rho=0.928\)</span>.</li>
<li>Q1. What is the minimum variance hedge ratio?</li>
<li>Q2. Each of the futures contract is for 42,000 gallons of heating oil. How many contracts does the airline need?</li>
</ul>
</section>
<section id="cross-hedge-and-risk-measures" class="slide level2">
<h2>Cross Hedge and Risk Measures</h2>
<ul>
<li><p>On date 0, an oil company expects to sell gasoline on date T. The gasoline price is normally distributed with the mean of $50 and the standard deviation of $3 per barrel. To hedge the risk, the company wants to use futures. However, the futures on gasoline is not available, so the company instead shorts futures on heating oil with the delivery on date T.</p>
<ul>
<li>The futures price of heating oil is $75.</li>
<li>The minimum variance hedge ratio is found to be 0.24.</li>
<li>The heating oil price is normally distributed with the mean of $80 and the standard deviation of $10 per barrel.</li>
<li>The correlation coefficient between the gasoline and heating oil prices is 0.8.</li>
</ul></li>
<li><p>Q1. What is the distribution of the total revenue (per barrel)?</p></li>
<li><p>Q2. With the hedgeing, what is the 5% bad outcome of the total revenue?</p></li>
</ul>
</section>
<section id="speculation-using-future" class="slide level2">
<h2>Speculation Using Future</h2>
<ul>
<li><p>Suppose you believe that crude oil prices are going to increase and therefore decide to purchase crude oil futures. Each contract calls for delivery of 1,000 barrels of oil, so for every $1 increase in the futures price of crude, the long position gains $1,000 and the short position loses that amount.</p>
<ul>
<li>If the futures price for delivery in February is $52 and crude oil is selling for $53, the long side will profit by $1,000 per contract purchased.</li>
</ul></li>
<li><p>Why does a speculator buy a futures contract? Why not buy the underlying asset directly?</p>
<ul>
<li>Lower transaction costs</li>
<li>Higher leverage (margin &lt; asset value)</li>
</ul></li>
</ul>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="chapter_forwards_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="chapter_forwards_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="chapter_forwards_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="chapter_forwards_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="chapter_forwards_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="chapter_forwards_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="chapter_forwards_files/libs/revealjs/plugin/reveal-text-resizer/revealjs-text-resizer.js"></script>
  <script src="chapter_forwards_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="chapter_forwards_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="chapter_forwards_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="chapter_forwards_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="chapter_forwards_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, RevealTextResizer, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>